title: Ny i utvikling og data
description: Oppsett for å komme i gang med utvikling og analyser i Nav for deg i utvikling og data
show_downloads: false
github:
  is_project_page: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
